### ISSUE TITLE
Commandline get stuck after execution AT+CMGS 

### ISSUE THREAD

**Issue by r00tb3** [beralt/atinout#3]
I've written a C file for executing AT commands sequentially as soon as I hit "AT+CMGS=XXXXXXXXX" command the program gets stuck and waits for a user interrupt then when I press Ctrl+C it executes the next command.

```
strcpy(command, "echo 'AT' | atinout - /dev/ttyUSB0 -");
        system(command);

strcpy(command, "echo 'AT+CMGF=1' | atinout - /dev/ttyUSB0 -");
        system(command);

strcpy(command, "echo -e 'AT+CMGS=\"1234567890\"' | atinout - /dev/ttyUSB0 -");
        system(command);

strcpy(command, "echo -e 'test messaget!!!!\x1A' | atinout - /dev/ttyUSB0 -");
        system(command);

```

Why does it get stuck?

How can I execute the above commands sequentially without the need of an interrupt?  

Is the problem with system command?

Regards.

**Comment by beralt** [comment]
It waits for an end-of-line character ("\n" for example) in the input, and scans the output of the modem for a character before returning. I'm guessing that it does not detect the ">" that the modem returns.

Note that the upstream of this project is here: http://atinout.sourceforge.net/index.html. I just patched the code to accept modems that only have a line-feed in the output.
